create table chairman_slaves (id bigint not null auto_increment, chairman_id bigint, primary key (id)) engine=InnoDB;
create table chairman_slaves_slaves (chairman_slaves_id bigint not null, slaves_id bigint not null, primary key (chairman_slaves_id, slaves_id)) engine=InnoDB;
create table roles (id bigint not null auto_increment, description varchar(255), name varchar(20), primary key (id)) engine=InnoDB;
create table user (id bigint not null, first_name varchar(255), is_active bit, last_name varchar(255), password varchar(255), patronymic varchar(255), username varchar(255), primary key (id)) engine=InnoDB;
create table user_id_sequence (next_val bigint) engine=InnoDB;
insert into user_id_sequence values ( 1 );
create table user_roles (user_id bigint not null, role_id bigint not null, primary key (user_id, role_id)) engine=InnoDB;
alter table chairman_slaves_slaves add constraint UK_pjc2bhpnorwam5j47stjud1s9 unique (slaves_id);
alter table user add constraint UK_sb8bbouer5wak8vyiiy4pf2bx unique (username);
alter table chairman_slaves add constraint FKno0kffhardgnbx26jf8qvrxjv foreign key (chairman_id) references user (id);
alter table chairman_slaves_slaves add constraint FK3s4wns1p0tumgtx4k07wx4fh foreign key (slaves_id) references user (id);
alter table chairman_slaves_slaves add constraint FKm04vx33vb37yydoh0inmujtdo foreign key (chairman_slaves_id) references chairman_slaves (id);
alter table user_roles add constraint FKh8ciramu9cc9q3qcqiv4ue8a6 foreign key (role_id) references roles (id);
alter table user_roles add constraint FK55itppkw3i07do3h7qoclqd4k foreign key (user_id) references user (id);