create table report (id bigint not null auto_increment, created_by varchar(255), created_date datetime(6), last_modified_by varchar(255), last_modified_date datetime(6), created datetime(6), data json, name varchar(255), status varchar(255), updated datetime(6), user_id bigint, primary key (id)) engine=InnoDB;
create table roles (id bigint not null auto_increment, description varchar(255), name varchar(20), primary key (id)) engine=InnoDB;
create table to_do (id bigint not null auto_increment, created_by varchar(255), created_date datetime(6), last_modified_by varchar(255), last_modified_date datetime(6), description varchar(255), text varchar(255), title varchar(255), user_id bigint, primary key (id)) engine=InnoDB;
create table user (id bigint not null, created_by varchar(255), created_date datetime(6), last_modified_by varchar(255), last_modified_date datetime(6), first_name varchar(255), is_active bit, last_name varchar(255), password varchar(255), patronymic varchar(255), username varchar(255), chairman_id bigint, primary key (id)) engine=InnoDB;
create table user_id_sequence (next_val bigint) engine=InnoDB;
insert into user_id_sequence values ( 2 );
create table user_roles (user_id bigint not null, role_id bigint not null, primary key (user_id, role_id)) engine=InnoDB;
alter table user add constraint unique_username unique (username);
alter table report add constraint report_author_id foreign key (user_id) references user (id) ON DELETE SET NULL ON UPDATE CASCADE;
alter table to_do add constraint to_do_author_id foreign key (user_id) references user (id) ON DELETE SET NULL ON UPDATE CASCADE;
alter table user add constraint follower_chairman foreign key (chairman_id) references user (id) ON DELETE SET NULL ON UPDATE CASCADE;
alter table user_roles add constraint user_roles_role foreign key (role_id) references roles (id);
alter table user_roles add constraint user_roles_user foreign key (user_id) references user (id);